version: '3'

services:
  project:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 80:8080
    volumes:
      - ./dist:/opt/project/dist:rw
      - ./src:/opt/project/src:ro
