version: '3'

networks:
  hello-jsx:
    driver: bridge
    external: false
    internal: false

services:
  data:
    image: robbtraister/mongo-vandelay
    environment:
      RESTORE: 'true'
    networks:
      hello-jsx:
        aliases:
          - db
          - database
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db:rw
      - ./data/dumps:/data/dumps:rw
      - ./data/restore:/data/restore:rw


  project:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      MONGO_URL: mongodb://data:27017/data
    networks:
      - hello-jsx
    ports:
      - 80:8080
    volumes:
      - ./dist:/opt/project/dist:rw
      - ./src:/opt/project/src:ro
